cacheFolder: ./.yarn/cache

changesetBaseRefs:
  - HEAD

enableGlobalCache: false

npmRegistries:
  //gitlab.com/api/v4/packages/npm/:
    npmAlwaysAuth: true
    npmAuthToken: "${GITLAB_GROUP_READ}"

npmScopes:
  finonex:
    npmRegistryServer: "https://gitlab.com/api/v4/packages/npm/"

yarnPath: .yarn/releases/yarn-4.0.2.cjs
